# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialexam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granted_wish',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
